//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aeonlb.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblHang> tblHangs { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblNhapKho> tblNhapKhoes { get; set; }
        public virtual DbSet<tblPhieuBanHang> tblPhieuBanHangs { get; set; }
        public virtual DbSet<tblYeuCauNhapKho> tblYeuCauNhapKhoes { get; set; }
        public virtual DbSet<tblChiTietNhapKho> tblChiTietNhapKhoes { get; set; }
        public virtual DbSet<tblChiTietPhieuBanHang> tblChiTietPhieuBanHangs { get; set; }
        public virtual DbSet<tblChiTietYeuCauNhap> tblChiTietYeuCauNhaps { get; set; }
    }
}
