//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aeonlb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietNhapKho
    {
        public string sMaHang { get; set; }
        public string sMaNhapKho { get; set; }
        public float fSoLuongThucNhap { get; set; }
    
        public virtual tblHang tblHang { get; set; }
        public virtual tblNhapKho tblNhapKho { get; set; }
    }
}
