//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aeonlb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietYeuCauNhap
    {
        public string sMaHang { get; set; }
        public string sMaYeuCauNhapKho { get; set; }
        public float fSoLuongYeuCau { get; set; }
    
        public virtual tblHang tblHang { get; set; }
        public virtual tblYeuCauNhapKho tblYeuCauNhapKho { get; set; }
    }
}
