//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aeonlb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHang()
        {
            this.tblChiTietNhapKhoes = new HashSet<tblChiTietNhapKho>();
            this.tblChiTietPhieuBanHangs = new HashSet<tblChiTietPhieuBanHang>();
            this.tblChiTietYeuCauNhaps = new HashSet<tblChiTietYeuCauNhap>();
        }
    
        public string sMaHang { get; set; }
        public string sTenHang { get; set; }
        public string sMotaHang { get; set; }
        public float fSLHienTai { get; set; }
        public string sDonViTinh { get; set; }
        public float fGiaBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietNhapKho> tblChiTietNhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuBanHang> tblChiTietPhieuBanHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietYeuCauNhap> tblChiTietYeuCauNhaps { get; set; }
    }
}
