//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aeonlb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhieuBaoHanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhieuBaoHanh()
        {
            this.tblChiTietPhieuBaoHanhs = new HashSet<tblChiTietPhieuBaoHanh>();
        }
    
        public string sMaPhieuBaoHanh { get; set; }
        public string sMaNhanVien { get; set; }
        public string sMaKhachHang { get; set; }
        public Nullable<System.DateTime> dThoiGianBaoHanh { get; set; }
        public string sTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietPhieuBaoHanh> tblChiTietPhieuBaoHanhs { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
